# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Bun Test Runner

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  bun-test:
    name: Bun tests

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Bun
      uses: antongolub/action-setup-bun@v1
    - run: bun install
    - run: bun run build
    - run: bun run mocha
